const paragraphs = [
  "If you understand how deep the love I have for you has become, you will be amazed and then think for a while for the possibility of such a level of passion for a human-like you. I actually mean what I am saying and I am not under the influence of alcohol. That's exactly how the condition of my heart is for you. I love you to the core, I need you all my life and will always do for all time because whoever has your type in his life is the luckiest ever. I love you my darling.If you understand how deep the love I have for you has become, you will be amazed and then think for a while for the possibility of such a level of passion for a human-like you. I actually mean what I am saying and I am not under the influence of alcohol. That's exactly how the condition of my heart is for you. I love you to the core, I need you all my life and will always do for all time because whoever has your type in his life is the luckiest ever. I love you my darling.",
  "couple of years back i was real begin to reactivating old hotmail accounts and using them to lodge in into fafsa book since this was in the heyday of chainmails with a hundred or so accounts there i had a huge backlog don't know why i did it a combination of boredom and verism i think and lots of free time i felt like a sort of hacker at least occasionally you stumble upon things you wish you weren't supposed to i mean yeah i know how that sounds once i came upon a guy's fafsa book and after a while you instantly realize it hasn't been used in years a bit like coming across an abandoned house tons of notifications and unopened pms on the top of the list of those messages it was a woman that kept trying to contact him my first impression was that it was a stalker maybe an ex that wasn't able to move on i really don't want to get into details because even for me it feels like i walked into an absolutely private matter but it was mostly her talking about her day-to-day stuff and occasionally begging him to come back sometimes it got real weird with her telling him how she felt him in the wind turns out the guy was dead and people have strange ways of coping i left that habit behind after that",
  "Introverts are looked down upon for lack of good 'communication skills'. Right from an early age, introverts have to compete very hard with peers, who seem to have no problem in public or interpersonal speaking. What seems to be effortless for peers is actually the most difficult task for an introverted child. And he is too young to even understand why, and too scared to admit this to anyone.",
  "When questions are especially interesting and difficult at the same time, as yours is, they tend to have several answers. We live because one day in early childhood we realise that we are alive and already have lots of reasons to go on living. These include the fact that there are many things about life that give us pleasure and happiness – even if sometimes we are sad, too, and sometimes ill: but these bad things pass. We live because of the happy things. We live because there are people who love us, and people we love back. We live because we want to find out things, and learn, and become able to do things that we would like to do. We live because others want us to, and we want them to live along with us. We live because we have hope, and want to see what happens next. I hope that lots of people live because they know life at its best can be wonderfully good, and want to help make it so: and that is a great reason for living.",
  "What happens in your final moments As dying progresses ?  the heart beats less strongly, blood pressure falls, skin cools down and nails become dusky. Internal organs function less as blood pressure drops. There may be periods of restlessness or moments of confusion, or just gradually deepening unconsciousness. We have no proven way to investigate what people experience during dying. Recent research shows that, even close to death, the unconscious brain responds to noises in the room. We don’t know how much sense music or voices make to a dying person, however.",
  "Why do I get attracted so easily to every girl I meet?  When we are not focused in our life we start getting attracted to every good looking thing of use to us. And girls are sexual and emotional requirements of a male so it's very easy to get attracted to them when you are null in your brain , it’s really normal and most of the guys are same . If you want to avoid this start doing something that you want to or love to you will never be attracted to every one",
  "What is the theory of relativity summary? Albert Einstein, in his theory of special relativity, determined that the laws of physics are the same for all non-accelerating observers, and he showed that the speed of light within a vacuum is the same no matter the speed at which an observer travels, according to Wired.",
  "A lucid dream is a type of dream where the dreamer becomes aware that they are dreaming. During a lucid dream, the dreamer may gain some amount of control over the dream characters, narrative, or environment; however, this is not actually necessary for a dream to be described as lucid",
];
